version: '3.7'
services:
  Postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=db
    - POSTGRES_USER=app
    - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
